'use server';
/**
 * @fileOverview A flow for generating text-to-speech audio using Gemini.
 *
 * - generateTts - A function that converts text to audio data.
 * - GenerateTtsInput - The input type for the generateTts function.
 * - GenerateTtsOutput - The return type for the generateTts function.
 */

import { ai } from '@/ai/genkit';
import { googleAI } from '@genkit-ai/google-genai';
import { z } from 'genkit';
import wav from 'wav';

const GenerateTtsInputSchema = z.object({
  text: z.string().describe('The text to be converted to speech.'),
});
export type GenerateTtsInput = z.infer<typeof GenerateTtsInputSchema>;

const GenerateTtsOutputSchema = z.object({
  audioData: z
    .string()
    .describe(
      "The generated audio as a data URI. Expected format: 'data:audio/wav;base64,<encoded_data>'."
    ),
});
export type GenerateTtsOutput = z.infer<typeof GenerateTtsOutputSchema>;

export async function generateTts(
  input: GenerateTtsInput
): Promise<GenerateTtsOutput> {
  return generateTtsFlow(input);
}

async function toWav(
  pcmData: Buffer,
  channels = 1,
  rate = 24000,
  sampleWidth = 2
): Promise<string> {
  return new Promise((resolve, reject) => {
    const writer = new wav.Writer({
      channels,
      sampleRate: rate,
      bitDepth: sampleWidth * 8,
    });

    const bufs: any[] = [];
    writer.on('error', reject);
    writer.on('data', function (d) {
      bufs.push(d);
    });
    writer.on('end', function () {
      resolve(Buffer.concat(bufs).toString('base64'));
    });

    writer.write(pcmData);
    writer.end();
  });
}

const generateTtsFlow = ai.defineFlow(
  {
    name: 'generateTtsFlow',
    inputSchema: GenerateTtsInputSchema,
    outputSchema: GenerateTtsOutputSchema,
  },
  async ({ text }) => {
    const { media } = await ai.generate({
      model: googleAI.model('gemini-2.5-flash-preview-tts'),
      config: {
        responseModalities: ['AUDIO'],
        speechConfig: {
          voiceConfig: {
            prebuiltVoiceConfig: { voiceName: 'Algenib' },
          },
        },
      },
      prompt: text,
    });

    if (!media) {
      throw new Error('No audio was generated by the model.');
    }

    const audioBuffer = Buffer.from(
      media.url.substring(media.url.indexOf(',') + 1),
      'base64'
    );

    const wavBase64 = await toWav(audioBuffer);

    return {
      audioData: `data:audio/wav;base64,${wavBase64}`,
    };
  }
);
